FROM microsoft/dotnet:2.1-sdk as backend
COPY ./backend/netcore /app/backendbuild
WORKDIR /app/backendbuild
RUN dotnet restore
RUN dotnet build
RUN dotnet ./src-test/Infrastructure.Test/bin/Debug/netcoreapp2.1/Infrastructure.Test.dll
RUN dotnet ./src-test/Web.Test/bin/Debug/netcoreapp2.1/Web.Test.dll
RUN dotnet publish -c Release -o /out
RUN cp -r src/Web/Configuration /out

FROM node:8.12.0-jessie as angularbase
ENV TZ=Australia/Melbourne
COPY ./ui/angular/app app/uibuild
WORKDIR app/uibuild
RUN apt-get update ;\
    apt-get install -y tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
RUN npm install -g @angular/cli

FROM angularbase as spa
RUN npm install
RUN ng build
RUN ng test --watch=false

FROM microsoft/dotnet:aspnetcore-runtime
EXPOSE 80
WORKDIR /app
COPY --from=backend /out .
COPY --from=spa /app/uibuild/dist/angular-auth-app ./app
ENTRYPOINT ["dotnet", "Web.dll"]