name: UIAngular
run-name: Build and Test UI Angular
on: 
  [push, workflow_dispatch]
  
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.path }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Detect if any files changed related to this build task
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          path:
            - 'ui/angular/**'
    - run: echo "🍏 This job's status is ${{ job.status }}."
     
  build-and-test-solution:
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: dotnet restore ./backend/netcore/Mvc.sln 
      - name: Build 
        run: dotnet build ./backend/netcore/Mvc.sln 
      - name: NPM install
        run: |
          cd ui/angular/app
          npm install -g --prefer-offline @angular/cli
          npm install --prefer-offline
          npx playwright install chromium
      - name: NPM build
        run: |
          cd ui/angular/app
          ng build
      - name: NPM test
        run: |
          cd ui/angular/app
          ng test --watch=false
      - name: Copy angular application
        run: |
          ls -r ui/angular/app/dist/angular-auth-app
          mkdir ./backend/netcore/src/Web/bin/Debug/net9.0/app
          cp -r ui/angular/app/dist/angular-auth-app/browser/* backend/netcore/src/Web/bin/Debug/net9.0/app
          ls -r backend/netcore/src/Web/bin/Debug/net9.0
      - name: Run application
        run: nohup dotnet run --project ./backend/netcore/src/Web/Web.csproj --launch-profile E2E &
      - name: Wait for the application to start
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:5000/alive; then
              echo " - Web app is up!"
              exit 0
            fi
            sleep 2
          done
          echo "Web app did not start in time."
          exit 1
      - name: Run e2e
        run: |
          cd ui/angular/app
          ng e2e
      - run: echo "🍏 This job's status is ${{ job.status }}."
