name: BackendOwinIdentityserver3
run-name: Build and Test Backend Owin-identityserver3
on: [push]
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.path }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Detect if any files changed related to this build task
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          path:
            - 'backend/owin-identityserver3/**'
    - run: echo "🍏 This job's status is ${{ job.status }}."
            
  build-and-test-solution:
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Restore Packages
        run: nuget restore ./backend/owin-identityserver3/OwinIdServer3.sln 
      - name: Build Solution
        run: msbuild.exe ./backend/owin-identityserver3/OwinIdServer3.sln
      - name: Test Solution
        run: | 
          vstest.console.exe "./backend/owin-identityserver3/Infrastructure.Test/bin/Debug/Infrastructure.Test.dll" /Logger:trx /TestAdapterPath:"./backend/owin-identityserver3/Infrastructure.Test/bin/Debug/"
          vstest.console.exe "./backend/owin-identityserver3/Web.Test/bin/Debug/Web.Test.dll" /Logger:trx /TestAdapterPath:"./backend/owin-identityserver3/Web.Test/bin/Debug/"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: test-results
          path: "**/*.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
      - run: echo "🍏 This job's status is ${{ job.status }}."